### ISSUE TITLE
Arduino Board Settings

### ISSUE THREAD

**Issue by Bibbbi** [RandomHacks-Git/Best-Improvement-RP2040#1]
Hello RandomHacks,

Which Arduino settings are you using to compile the source code?

![Settings](https://user-images.githubusercontent.com/34800528/165235850-f9e62c03-4b85-47b2-8bc7-a5f6dbb94cdc.png)

**Comment by RandomHacks-Git** [comment]
Hi, 

You need to select "Generic RP2040" on the board menu and "Adafruit TinyUSB" for the USB Stack. 

BTW, I just updated the code so you might want to download the source code again.

If you just want to update the firmware without modifying anything you can use the precompiled versions here: https://github.com/RandomHacks-Git/Best-Improvement-RP2040/releases/

**Comment by Bibbbi** [comment]
Hello RandomHacks,

Thank you for the information and the reference to the finished compiled version.
It would just be good to know if I ever get the idea to change or extend your code.

Are these the correct Arduino board settings?

![image](https://user-images.githubusercontent.com/34800528/165284090-9cf1a818-aadf-4b82-85ed-0407d30ad930.png)

**Comment by RandomHacks-Git** [comment]
Yes that is correct 👍
